name: shelf_serve_mvc
description: A simple MVC framework for shelf.
version: 1.0.0-dev.2
repository:  https://github.com/yiiim/shelf_serve_mvc

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  web_socket_channel: ^2.4.0
  shelf_web_socket: ^1.0.4
  dart_dependency_injection: ^1.0.1+10
  shelf_multipart: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
